include: package:lints/recommended.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    always_declare_return_types: true
    avoid_dynamic_calls: true
    avoid_escaping_inner_quotes: true
    avoid_setters_without_getters: true
    cast_nullable_to_non_nullable: true
    close_sinks: true
    no_adjacent_strings_in_list: true
    no_default_cases: true
    omit_local_variable_types: true
    only_throw_errors: true
    prefer_interpolation_to_compose_strings: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    sort_pub_dependencies: true
    test_types_in_equals: true
    unawaited_futures: true
    unnecessary_parenthesis: true
    unnecessary_statements: true
    unsafe_html: true

    # Excluded from recommended.yaml & core.yaml
    provide_deprecation_message: false
    prefer_function_declarations_over_variables: false
    unnecessary_overrides: false # remove when mockito is fixed

    # From flutter_lints
    avoid_print: false
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    no_logic_in_create_state: true
    prefer_const_constructors: false
    prefer_const_constructors_in_immutables: false
    prefer_const_declarations: false
    prefer_const_literals_to_create_immutables: false
    sized_box_for_whitespace: true
    use_full_hex_values_for_flutter_colors: true
    use_key_in_widget_constructors: false
