// GENERATED CODE - DO NOT MODIFY BY HAND

import 'week_data.dart';

/// Week conventions per region (ISO 3166), with "001" as the world default.
const weekDataByRegion = <String, WeekInfo>{
  '001': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'AD': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'AE': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'AF': WeekInfo(
    firstDayOfWeek: 6,
    weekendStart: 4,
    weekendEnd: 5,
    minDaysInFirstWeek: 1,
  ),
  'AG': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'AI': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'AL': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'AM': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'AN': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'AR': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'AS': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'AT': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'AU': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'AX': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'AZ': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'BA': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'BD': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'BE': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'BG': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'BH': WeekInfo(
    firstDayOfWeek: 6,
    weekendStart: 5,
    weekendEnd: 6,
    minDaysInFirstWeek: 1,
  ),
  'BM': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'BN': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'BR': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'BS': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'BT': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'BW': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'BY': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'BZ': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'CA': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'CH': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'CL': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'CM': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'CN': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'CO': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'CR': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'CY': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'CZ': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'DE': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'DJ': WeekInfo(
    firstDayOfWeek: 6,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'DK': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'DM': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'DO': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'DZ': WeekInfo(
    firstDayOfWeek: 6,
    weekendStart: 5,
    weekendEnd: 6,
    minDaysInFirstWeek: 1,
  ),
  'EC': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'EE': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'EG': WeekInfo(
    firstDayOfWeek: 6,
    weekendStart: 5,
    weekendEnd: 6,
    minDaysInFirstWeek: 1,
  ),
  'ES': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'ET': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'FI': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'FJ': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'FO': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'FR': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'GB': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'GE': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'GF': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'GP': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'GR': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'GT': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'GU': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'HK': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'HN': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'HR': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'HU': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'ID': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'IE': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'IL': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 5,
    weekendEnd: 6,
    minDaysInFirstWeek: 1,
  ),
  'IN': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 7,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'IQ': WeekInfo(
    firstDayOfWeek: 6,
    weekendStart: 5,
    weekendEnd: 6,
    minDaysInFirstWeek: 1,
  ),
  'IR': WeekInfo(
    firstDayOfWeek: 6,
    weekendStart: 5,
    weekendEnd: 5,
    minDaysInFirstWeek: 1,
  ),
  'IS': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'IT': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'JM': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'JO': WeekInfo(
    firstDayOfWeek: 6,
    weekendStart: 5,
    weekendEnd: 6,
    minDaysInFirstWeek: 1,
  ),
  'JP': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'KE': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'KG': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'KH': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'KR': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'KW': WeekInfo(
    firstDayOfWeek: 6,
    weekendStart: 5,
    weekendEnd: 6,
    minDaysInFirstWeek: 1,
  ),
  'KZ': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'LA': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'LB': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'LI': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'LK': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'LT': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'LU': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'LV': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'LY': WeekInfo(
    firstDayOfWeek: 6,
    weekendStart: 5,
    weekendEnd: 6,
    minDaysInFirstWeek: 1,
  ),
  'MC': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'MD': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'ME': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'MH': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'MK': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'MM': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'MN': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'MO': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'MQ': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'MT': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'MV': WeekInfo(
    firstDayOfWeek: 5,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'MX': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'MY': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'MZ': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'NI': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'NL': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'NO': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'NP': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'NZ': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'OM': WeekInfo(
    firstDayOfWeek: 6,
    weekendStart: 5,
    weekendEnd: 6,
    minDaysInFirstWeek: 1,
  ),
  'PA': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'PE': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'PH': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'PK': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'PL': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'PR': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'PT': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'PY': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'QA': WeekInfo(
    firstDayOfWeek: 6,
    weekendStart: 5,
    weekendEnd: 6,
    minDaysInFirstWeek: 1,
  ),
  'RE': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'RO': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'RS': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'RU': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'SA': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 5,
    weekendEnd: 6,
    minDaysInFirstWeek: 1,
  ),
  'SD': WeekInfo(
    firstDayOfWeek: 6,
    weekendStart: 5,
    weekendEnd: 6,
    minDaysInFirstWeek: 1,
  ),
  'SE': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'SG': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'SI': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'SK': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'SM': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'SV': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'SY': WeekInfo(
    firstDayOfWeek: 6,
    weekendStart: 5,
    weekendEnd: 6,
    minDaysInFirstWeek: 1,
  ),
  'TH': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'TJ': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'TM': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'TR': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'TT': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'TW': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'UA': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'UG': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 7,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'UM': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'US': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'UY': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'UZ': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'VA': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 4,
  ),
  'VE': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'VI': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'VN': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'WS': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'XK': WeekInfo(
    firstDayOfWeek: 1,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'YE': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 5,
    weekendEnd: 6,
    minDaysInFirstWeek: 1,
  ),
  'ZA': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
  'ZW': WeekInfo(
    firstDayOfWeek: 7,
    weekendStart: 6,
    weekendEnd: 7,
    minDaysInFirstWeek: 1,
  ),
};

/// Likely region for region-less locales (derived from CLDR likelySubtags).
const likelyRegion = <String, String>{
  'af': 'ZA',
  'am': 'ET',
  'ar': 'EG',
  'as': 'IN',
  'az': 'AZ',
  'az-Latn': 'AZ',
  'be': 'BY',
  'bg': 'BG',
  'bn': 'BD',
  'bs': 'BA',
  'bs-Latn': 'BA',
  'ca': 'ES',
  'chr': 'US',
  'cs': 'CZ',
  'cy': 'GB',
  'da': 'DK',
  'de': 'DE',
  'dsb': 'DE',
  'el': 'GR',
  'en': 'US',
  'es': 'ES',
  'et': 'EE',
  'eu': 'ES',
  'fa': 'IR',
  'fi': 'FI',
  'fil': 'PH',
  'fr': 'FR',
  'ga': 'IE',
  'gd': 'GB',
  'gl': 'ES',
  'gu': 'IN',
  'ha': 'NG',
  'he': 'IL',
  'hi': 'IN',
  'hi-Latn': 'IN',
  'hr': 'HR',
  'hsb': 'DE',
  'hu': 'HU',
  'hy': 'AM',
  'id': 'ID',
  'ig': 'NG',
  'is': 'IS',
  'it': 'IT',
  'ja': 'JP',
  'jv': 'ID',
  'ka': 'GE',
  'kk': 'KZ',
  'kk-Cyrl': 'KZ',
  'km': 'KH',
  'kn': 'IN',
  'ko': 'KR',
  'kok': 'IN',
  'kok-Deva': 'IN',
  'ky': 'KG',
  'lo': 'LA',
  'lt': 'LT',
  'lv': 'LV',
  'mk': 'MK',
  'ml': 'IN',
  'mn': 'MN',
  'mr': 'IN',
  'ms': 'MY',
  'my': 'MM',
  'nb': 'NO',
  'ne': 'NP',
  'nl': 'NL',
  'nn': 'NO',
  'no': 'NO',
  'or': 'IN',
  'pa': 'IN',
  'pa-Guru': 'IN',
  'pcm': 'NG',
  'pl': 'PL',
  'ps': 'AF',
  'pt': 'BR',
  'ro': 'RO',
  'ru': 'RU',
  'sd': 'PK',
  'sd-Arab': 'PK',
  'si': 'LK',
  'sk': 'SK',
  'sl': 'SI',
  'so': 'SO',
  'sq': 'AL',
  'sr': 'RS',
  'sr-Cyrl': 'RS',
  'sr-Latn': 'RS',
  'sv': 'SE',
  'sw': 'TZ',
  'ta': 'IN',
  'te': 'IN',
  'th': 'TH',
  'ti': 'ET',
  'tk': 'TM',
  'tr': 'TR',
  'uk': 'UA',
  'ur': 'PK',
  'uz': 'UZ',
  'uz-Latn': 'UZ',
  'vi': 'VN',
  'yo': 'NG',
  'yue': 'HK',
  'yue-Hans': 'CN',
  'yue-Hant': 'HK',
  'zh': 'CN',
  'zh-Hans': 'CN',
  'zh-Hant': 'TW',
  'zu': 'ZA',
};
